language: python
python:
  - "3.6"
sudo: false
addons:
  ssh_known_hosts:
    - github.com
    - ssh.github.com
    - 192.30.253.*
install:
  # clone parser script
  - git clone https://github.com/kiesproject/prepass-parser parser
  - cd parser
  # install dependencies
  - pip install -r requirement.txt
  - cd -
before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_231fca80d907_key -iv $encrypted_231fca80d907_iv -in travis.enc -out deploy -d
  - cp deploy ~/.ssh/
  - chmod 600 ~/.ssh/deploy
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/deploy
script:
  - cd parser
  - python parser.py opendata.json
  - mv opendata.json last-update.json ../
  - cd -
after_success:
  - git config --global user.name "Deployment Bot"
  - git config --global user.email "deploy@example.com"
  - git checkout master
  - git add opendata.json last-update.json
  - git commit -m "Update `date +"%Y/%m/%d %H:%M:%S"` [skip ci]"
  - git push git@github.com:kiesproject/prepass-opendata.git master
